DATA_ROOT = "/data/jim/CMB_Data/"
ASSETS_DIRECTORY = f"{DATA_ROOT}/Assets/Planck/"
PLANCK_NOISE_DIRECTORY = f"{DATA_ROOT}/Assets/PlanckNoise/"
DATASETS_DIRECTORY = f"{DATA_ROOT}/Datasets/"
PATH_CLEANED_MAP_NILC = f"{ASSETS_DIRECTORY}/COM_CMB_IQU-nilc_2048_R3.00_full.fits"
PATH_CLEANED_PS = f"{ASSETS_DIRECTORY}/Planck/COM_PowerSpect_CMB-base-plikHM-TTTEEE-lowl-lowE-lensing-minimum-theory_R3.01.txt"
PATH_LOW_RES_MAP = f"{DATASETS_DIRECTORY}/I_128_1450/Simulation/Valid/sim0000/obs_100_map.fits"